[project]
name = "area-calculator-osu"
version = "0.2.1"
description = "TODO"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.4",
    "pynput>=1.8.1",
    "typer>=0.15.2",
]
